-- Generated by scripts/build_pg_seed_dumps.py (SQLAlchemy metadata)

BEGIN;

CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);


CREATE TABLE addresses (
	id SERIAL NOT NULL, 
	postal_code VARCHAR(6), 
	address_text VARCHAR(1000) NOT NULL, 
	city VARCHAR(128), 
	district VARCHAR(256), 
	street VARCHAR(512), 
	house VARCHAR(64), 
	latitude NUMERIC(10, 7) NOT NULL, 
	longitude NUMERIC(10, 7) NOT NULL, 
	is_private BOOLEAN, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_addresses_latitude CHECK (latitude BETWEEN -90 AND 90), 
	CONSTRAINT ck_addresses_longitude CHECK (longitude BETWEEN -180 AND 180), 
	CONSTRAINT ck_addresses_text CHECK (length(trim(address_text)) > 0), 
	UNIQUE (address_text)
)

;

CREATE INDEX ix_addresses_postal_code ON addresses (postal_code);

CREATE INDEX ix_addresses_city ON addresses (city);

CREATE INDEX ix_addresses_district ON addresses (district);


CREATE TABLE mc_parser_cursors (
	source_key VARCHAR(64) NOT NULL, 
	backfill_complete BOOLEAN NOT NULL, 
	oldest_seen_at TIMESTAMP WITH TIME ZONE, 
	newest_seen_at TIMESTAMP WITH TIME ZONE, 
	listing_cursor VARCHAR(512), 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	last_error TEXT, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (source_key)
)

;


CREATE TABLE news_parser_cursors (
	source_key VARCHAR(64) NOT NULL, 
	backfill_complete BOOLEAN NOT NULL, 
	oldest_seen_at TIMESTAMP WITH TIME ZONE, 
	newest_seen_at TIMESTAMP WITH TIME ZONE, 
	listing_cursor VARCHAR(512), 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	last_error TEXT, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (source_key)
)

;


CREATE TABLE users (
	id SERIAL NOT NULL, 
	max_user_id BIGINT NOT NULL, 
	name VARCHAR(255), 
	username VARCHAR(255), 
	chat_id BIGINT, 
	start_payload VARCHAR(128), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
)

;

CREATE UNIQUE INDEX ix_users_max_user_id ON users (max_user_id);

CREATE INDEX ix_users_username ON users (username);


CREATE TABLE chats (
	chat_id BIGINT NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	invite_link VARCHAR(2048), 
	chat_type VARCHAR(16), 
	address_id INTEGER NOT NULL, 
	PRIMARY KEY (chat_id), 
	FOREIGN KEY(address_id) REFERENCES addresses (id) ON DELETE RESTRICT
)

;

CREATE INDEX ix_chats_address_id ON chats (address_id);

CREATE INDEX ix_chats_chat_type ON chats (chat_type);


CREATE TABLE events (
	id SERIAL NOT NULL, 
	title VARCHAR(512) NOT NULL, 
	body TEXT NOT NULL, 
	importance INTEGER NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	address_id INTEGER, 
	geo_by VARCHAR(16), 
	weight FLOAT NOT NULL, 
	source_msg_id VARCHAR(128), 
	disaster_flag BOOLEAN NOT NULL, 
	source_url VARCHAR(1024), 
	image_url VARCHAR(2048), 
	published_at TIMESTAMP WITH TIME ZONE, 
	active_from TIMESTAMP WITH TIME ZONE, 
	active_to TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(address_id) REFERENCES addresses (id) ON DELETE SET NULL
)

;

CREATE INDEX ix_events_importance ON events (importance);

CREATE INDEX ix_events_source ON events (source);

CREATE INDEX ix_events_weight ON events (weight);

CREATE INDEX ix_events_published_at ON events (published_at);

CREATE UNIQUE INDEX uq_events_source_msg ON events (source, source_msg_id) WHERE source_msg_id IS NOT NULL;

CREATE INDEX ix_events_geo_by ON events (geo_by);

CREATE INDEX ix_events_active_from ON events (active_from);

CREATE INDEX ix_events_source_msg_id ON events (source_msg_id);

CREATE INDEX ix_events_active_to ON events (active_to);

CREATE INDEX ix_events_address_id ON events (address_id);


CREATE TABLE chat_links (
	id SERIAL NOT NULL, 
	token VARCHAR(32) NOT NULL, 
	requester_user_id INTEGER NOT NULL, 
	admin_user_id INTEGER, 
	address_id INTEGER NOT NULL, 
	chat_id BIGINT, 
	status VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (token), 
	FOREIGN KEY(requester_user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(admin_user_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(address_id) REFERENCES addresses (id) ON DELETE RESTRICT, 
	FOREIGN KEY(chat_id) REFERENCES chats (chat_id) ON DELETE SET NULL
)

;

CREATE INDEX ix_chat_links_status ON chat_links (status);

CREATE INDEX ix_chat_links_requester_user_id ON chat_links (requester_user_id);

CREATE INDEX ix_chat_links_address_id ON chat_links (address_id);


CREATE TABLE users_chat (
	user_id INTEGER NOT NULL, 
	chat_id BIGINT NOT NULL, 
	PRIMARY KEY (user_id, chat_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(chat_id) REFERENCES chats (chat_id) ON DELETE CASCADE
)

;

CREATE INDEX ix_users_chat_chat_id ON users_chat (chat_id);

INSERT INTO alembic_version (version_num) VALUES ('0013_events_active_window') ON CONFLICT DO NOTHING;

COMMIT;
